%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 643.5951111267952
Camera1.fy: 642.6656126857330
Camera1.cx: 475.2215406900663
Camera1.cy: 307.4120184196884

Camera1.k1: -0.061606731291039
Camera1.k2: 0.100129900708930
Camera1.p1: 0.0
Camera1.p2: 0.0
Camera1.k3: 0.0

Camera2.fx: 645.5637158104681
Camera2.fy: 644.6523115974766
Camera2.cx: 471.2755868675698
Camera2.cy: 304.2698424873490

Camera2.k1: -0.060194715488128
Camera2.k2: 0.097872361377687
Camera2.p1: 0.0
Camera2.p2: 0.0
Camera2.k3: 0.0

Camera.width: 960
Camera.height: 600

# Camera frames per second 
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

Stereo.ThDepth: 65.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.999998014036002,0.00198830274020040,-0.000136294769609574,0.254050495932918,
        -0.00198877987385306,0.999991560748650,-0.00359488332102552,0.000751574674544885,
         0.000129145903025813,0.00359514724201139,0.999993529097886,-0.00145530195199421,
         0.0,0.0,0.0,1.0]

IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [9.588005232696872e-05,0.02165642738051793,0.9997654674773117,8.9253240841861001e-02,
         -0.999887438936744,-0.01499774692618039,0.0004207655603527538,1.6994609051096400e-01,
          0.01500334174556117,-0.99965297315631,0.02165255172526581,3.8671653069226000e-02,
          0.0,0.0,0.0,1.0]
IMU.NoiseGyro: 0.0002495875336978279 # 1.6968e-04
IMU.NoiseAcc: 0.0016744851413197843 # 2.0000e-3
IMU.GyroWalk: 4.901714002449629e-06
IMU.AccWalk: 6.244967184390112e-05 # 3.0000e-3
IMU.Frequency: 200.0
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0

System.LoopClosing: 0
