# down-sample of dataset frequency:
down_sample_ratio: 20

# bag absolute path
input_bag_path: /media/yaya/p3600/
bag_name: timed_1018_13.bag
# output folder path (must exist, for image saving):
output_folder_path: /media/yaya/p3600/image_test/
output_image_prefix: image_
output_image_format: .png

# cam topics in rosbag:
cam_topic: /dalsa_gray/left/image_raw