# down-sample of dataset frequency:
down_sample_ratio: 1

# bag absolute path
input_bag_path: /media/spiderman/zhipeng_8t/datasets/BotanicGarden/1018-00/
bag_name: 1018_00_img10hz600p.bag
# output folder path (must exist, for image saving):
output_folder_path: /media/spiderman/zhipeng_8t/datasets/BotanicGarden/1018-00/1018_00_img10hz600p/gt/
output_gt_prefix: ""
output_gt_format: .csv

# cam topics in rosbag:
gt_topic: /gt_poses