# down-sample of dataset frequency:
down_sample_ratio: 1

# bag absolute path
input_bag_path: /mnt/lboro_nas/personal/Zhipeng/hortimul_review/indoor_lab2/
bag_name: indoor_lab2.bag
# output folder path (must exist, for image saving):
output_folder_path: /mnt/lboro_nas/personal/Zhipeng/hortimul_review/indoor_lab2/ms_imu/
output_imu_prefix: ""

# cam topics in rosbag:
imu_topic: /ms/imu/data
