# down-sample of dataset frequency:
down_sample_ratio: 1

# bag absolute path
input_bag_path: /media/spiderman/zhipeng_8t/datasets/BotanicGarden/1018-00/
bag_name: 1018_00_img10hz600p.bag
# output folder path (must exist, for image saving):
output_folder_path: /media/spiderman/zhipeng_8t/datasets/BotanicGarden/1018-00/1018_00_img10hz600p/left_gray/
output_image_prefix: ""
output_image_format: .png

# cam topics in rosbag:
cam_topic: /dalsa_gray/left/image_raw