# down-sample of dataset frequency:
down_sample_ratio: 1

# bag absolute path
input_bag_path: /media/spiderman/zhipeng_8t1/datasets/lab_outside_test/imu_test/slow/
bag_name: slow.bag
# output folder path (must exist, for image saving):
output_folder_path: /media/spiderman/zhipeng_8t1/datasets/lab_outside_test/imu_test/slow/
output_imu_prefix: ""

# cam topics in rosbag:
imu_topic: /ms/imu/data
