# down-sample of dataset frequency:
down_sample_ratio: 1

# bag absolute path
input_bag_path: /media/spiderman/zhipeng_8t1/datasets/lab_outside_test/datasetTest_2026-02-06-16-14-30/
bag_name: datasetTest_2026-02-06-16-14-30.bag
# output folder path (must exist, for image saving):
output_folder_path: /media/spiderman/zhipeng_8t1/datasets/lab_outside_test/datasetTest_2026-02-06-16-14-30/forwardLeft/
output_image_prefix: ""
output_image_format: .png

# cam topics in rosbag:
cam_topic: /forwardLeft/image_raw/compressed