# down-sample of dataset frequency:
down_sample_ratio: 1

# bag absolute path
input_bag_path: /media/spiderman/zhipeng_8t1/datasets/BotanicGarden/1008-01/
bag_name: gt_1008_01_qnew.bag
output_folder_path: /media/spiderman/zhipeng_8t1/datasets/BotanicGarden/1008-01/
output_gt_prefix: ""
output_name: 1008_01_GT_output

# cam topics in rosbag:
gt_topic: /gt_poses
